name = input('Enter your name:')
print('I am the Fots virtual assistant. Hello',name)
q = input('How can I help you?')
print('I will try to help with that')
also = input('Is there anything else you need because Im going to take a break soon?')
print('Im sorry the Fots Virtual Assistant does not know how to do that. TRY A RISPE FOT AND MAYBE YOULL FEE BETTER.')
rating = input('How did you like the Fots Virtual Assistant? One out of five')
print('Thank you for rating me a', rating)
print('Happy fotting!')
did = input('If this didnt help please describe your issue:')
print('I see you need help with:',did)
website = input('Which FOTS website are you using?')
print('I recomment you go to https://lb123658.github.io/Fots/ for a better experience. Contact Fots at fotsofficial671@gmail.com')
